### ISSUE TITLE
Error Task exception was never retrieved

### ISSUE THREAD

**Issue by Arcade75** [Hassassistant/OpenMindsAI#3]
Hello

Thanks for your integration. I have this error and I am pretty sure I have followed all the steps:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/openmindsai/sensor.py", line 69, in async_ask
response = await self._hass.async_add_executor_job(ask, self._session_cookie, self._model, new_query)
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/config/custom_components/openmindsai/sensor.py", line 31, in ask
response_message = response_json[0]["response"]
KeyError: 0

Thanks

**Comment by Hassassistant** [comment]
could you provide you configuration.yaml?
assuming you remembered to restart home assistant etc too?

**Comment by Arcade75** [comment]
Thanks for your help. I have added this to configuration.yaml (I have deteled some of the characters in the middle of the session cookie, but the lenth seems to be the same as yours )

input_text:
  gpt_prompt:
    initial: ""
    max: 255
## This is the input_text entity you'll use to send prompts.

and this to sensor.yaml as I got an error in configuration.yaml when I ttried to save it

- platform: openmindsai
  name: "hassio_mindsdb_response"
## Optional. Defaults to hassio_mindsdb_response
  input_name: "gpt_prompt"
## Optional. Defaults to gpt_prompt. This is your input_text name
  session_cookie: ".eJw9i8sKwyAQRf_lrl048dH      jyA.IrFy865ssrRsVcT3V9dwzsrGs4E"
## Required. This is your MindsDB Session Cookie
  model: "gpt4hassioJG3"
## Required. This is your MindsDB Model Name

**Comment by Arcade75** [comment]
Update: now all is in the configuration.yaml file, I found out the error:

input_text:
  gpt_prompt:
    initial: ""
    max: 255


sensor:
  - platform: openmindsai
    name: "hassio_mindsdb_response"
    input_name: "gpt_prompt"
    session_cookie: ".eJw9i8sKwyAQRf_lrl048dHGnxGZTEBobFBTKKH_Xsk         0BxYAkVQ.ZFBjyA.IrFy865ssrRsVcT3V9dwzsrGs4E"
    model: "gpt4hassioJG3"

**Comment by Arcade75** [comment]
I have tried again with new session_cookie and I have the same error

**Comment by Arcade75** [comment]
Is there anything I can try to make this work? Thanks

**Comment by aeleos** [comment]
@Arcade75 @Hassassistant 

I ran into this issue and resolved it, the issue is that the instructions for copying the cookie are incorrect. On my version of chrome, this results in most of the cookie not being copied. This is how I did it:

1. Find the home source in the network tab
2. Right click on home, select Copy -> Copy as cURL (cmd or bash)
3. Paste the resulting command into a text editor and locate the 'session=' parameter 
4. Copy the session cookie, excluding the trailing " or '
5. Paste this into the configuration

**Comment by Arcade75** [comment]
Thanks! You are right, it is a little bit tricky to read all the code. I tried that and it seems I got the full session cookie but still get the same error :(

**Comment by aeleos** [comment]
Its likely you have some other error with the session cookie. The code is just passing it simply to an API call, so there isn't much that could be going wrong. I have been having good success with it.

**Comment by rolfberkenbosch** [comment]
Make sure you comfirmed your account with your email.
