### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by andiukas** [Hassassistant/OpenMindsAI#4]
Integration stop working:

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/openmindsai/sensor.py", line 69, in async_ask
    response = await self._hass.async_add_executor_job(ask, self._session_cookie, self._model, new_query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmindsai/sensor.py", line 31, in ask
    response_message = response_json[0]["response"]
                       ~~~~~~~~~~~~~^^^
KeyError: 0

**Comment by gielk** [comment]
Same for me.

**Comment by gielk** [comment]
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/openmindsai/sensor.py:31
Integration: openmindsai (documentation)
First occurred: 21:35:14 (12 occurrences)
Last logged: 21:35:32

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/openmindsai/sensor.py", line 69, in async_ask
    response = await self._hass.async_add_executor_job(ask, self._session_cookie, self._model, new_query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmindsai/sensor.py", line 31, in ask
    response_message = response_json[0]["response"]
                       ~~~~~~~~~~~~~^^^
KeyError: 0

**Comment by gieljnssns** [comment]
I had this error also.
I had to confirm my email in the mindsdb settings menu.
