### ISSUE TITLE
Not working. Error in logs

### ISSUE THREAD

**Issue by Jurgenn22** [Hassassistant/OpenMindsAI#6]
Hi,

Hi It doesn't work at the moment. I get the following error in the logs.

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/openmindsai/sensor.py", line 69, in async_ask
    response = await self._hass.async_add_executor_job(ask, self._session_cookie, self._model, new_query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmindsai/sensor.py", line 31, in ask
    response_message = response_json[0]["response"]
                       ~~~~~~~~~~~~~^^^
KeyError: 0

**Comment by Jurgenn22** [comment]
Hi,
It was my config, everything works again.

**Comment by wsjunior1985** [comment]
Same problem here, what was the problem with your config?

**Comment by gieljnssns** [comment]
https://github.com/Hassassistant/OpenMindsAI/issues/4#issuecomment-1661728799

**Comment by Jurgenn22** [comment]
@wsjunior1985 
Hi,
It was the config, incorrectly copied piece of the session cookie.

**Comment by gielk** [comment]
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/openmindsai/sensor.py:31
Integration: openmindsai (documentation)
First occurred: 09:56:41 (4 occurrences)
Last logged: 10:05:07

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/openmindsai/sensor.py", line 69, in async_ask
    response = await self._hass.async_add_executor_job(ask, self._session_cookie, self._model, new_query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/openmindsai/sensor.py", line 31, in ask
    response_message = response_json[0]["response"]
                       ~~~~~~~~~~~~~^^^
KeyError: 0

```

I have the same problem, I double-checked the config, but this is correct. @wsjunior1985 did u find what your issue was?

**Comment by rolfberkenbosch** [comment]
Make sure you comfirmed your account with your email.
